# Generated by Django 5.0.3 on 2024-03-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placename', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=1048)),
            ],
        ),
    ]
